# note: this was created using chatgpt
name: Update release on source change
on:
  push:
    paths:
      - "source/**"
      - "!source/README.md"
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            source

      - name: Zip files
        run: |
          mkdir release_files
          zip -r release_files/source.zip source -x "source/README-md"

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          name: 'Automated release ${{ github.run_number }}.'
          files: release_files/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

