# note: this was created using chatgpt
name: Update release on source change

on:
  push:
    paths:
      - "source/**"
      - "!source/README.md"
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            source

      - name: Zip files
        run: |
          mkdir release_files
          zip -r release_files/source.zip source -x "source/README-md"
      
      - name: Get latest release
        id: get_latest_release
        run: |
          latest_tag=$(git ls-remote --tags origin | awk '{print $2}' | sed 's|refs/tags/||' | sort -V | tail -n1)
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Create release
        id: update_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          name: 'Release loader files'
          files: release_files/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

