# note: this was created using chatgpt
name: Update release on source change

on:
  push:
    paths:
      - "source/**"
      - "!source/README.md"
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            source

      - name: Zip files
        run: |
          cd source/
          zip -r source.zip * -x "README.md"

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          name: 'Release 1.0.0 Alpha'
          files: source/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

